name: online
version: '0.3.0.0'
synopsis: online statistics
description: transformation of statistics to online algorithms
category: statistics
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day
license: BSD3
github: tonyday567/online
extra-source-files:
  - stack.yaml
default-extensions:
  - NegativeLiterals
  - NoImplicitPrelude
  - OverloadedStrings
  - UnicodeSyntax
library:
  source-dirs: src
  ghc-options:
    -Wall
    -Wcompat
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wredundant-constraints
  exposed-modules:
    - Online
    - Online.Averages
    - Online.Medians
    - Online.Quantiles
  dependencies:
    - base >=4.7 && <5
    - foldl
    - numhask-prelude
    - protolude
    - tdigest
    - vector
    - vector-algorithms
tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
      - base >=4.7 && <5
      - protolude
      - tasty
      - doctest
