name: online
version: '0.2.1.0'
synopsis: online statistics
description: transformation of statistics to online algorithms
category: statistics
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day
license: BSD3
github: tonyday567/online
extra-source-files:
- readme.md
- stack.yaml
default-extensions:
- NegativeLiterals
- NoImplicitPrelude
- OverloadedStrings
- UnicodeSyntax
dependencies:
- protolude
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Online
  - Online.Averages
  - Online.Medians
  - Online.Quantiles
  dependencies:
  - base >=4.7 && <5
  - foldl
  - numhask
  - tdigest
  - vector
  - vector-algorithms
executables:
  online-bench:
    main: bench.hs
    source-dirs: bench
    ghc-options:
    - -O2
    - -funbox-strict-fields
    - -fforce-recomp
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >=4.7 && <5
    - foldl
    - formatting
    - numhask
    - online
    - optparse-generic
    - perf
    - scientific
    - text
tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
    - base >=4.7 && <5
    - tasty
    - doctest
