resolver: lts-13.21

packages:
  - online
  - online-bench
  - ../numhask/numhask
  - ../numhask/numhask-prelude
  - ../numhask/numhask-space

extra-deps:
  - perf-analysis-0.0.1.1
  - perf-0.4.1.0
  - rdtsc-1.3.0.1
  # - tdigest-0.2

# allow-newer: true
