resolver: lts-14.13

packages:
  - online
  - online-bench

extra-deps:
  - perf-analysis-0.2.0.0
  - perf-0.5.0.0
  - rdtsc-1.3.0.1
  - readme-lhs-0.2.2
  - tdigest-0.2.1
  - pandoc-2.7.3
  - pandoc-types-1.17.6.1
