name: online-bench
version: '0.0.1.0'
synopsis: online benchmarking
description: benchmarking of online library
category: statistics
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day
license: BSD3
github: tonyday567/online
extra-source-files:
  - stack.yaml
default-extensions:
  - NegativeLiterals
  - NoImplicitPrelude
  - OverloadedStrings
  - UnicodeSyntax
executables:
  online-bench:
    main: bench.hs
    source-dirs: ./
    ghc-options:
      - -O2
      - -funbox-strict-fields
      - -fforce-recomp
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >=4.7 && <5
      - foldl
      - formatting
      - numhask-prelude
      - online
      - optparse-generic
      - perf
      - perf-analysis
      - protolude
      - scientific
      - tdigest
      - text
